ios-deploy.c

Just a pair of useful utility options for creating directories and removing files. `--rm` doesn't handle removing non-empty directories currently. It wouldn't be that hard to add, you'd just have to iterate over the contents and remove them all if the call to `AFCRemovePath` fails. Presumably you'd want this to be an option, like `rm -r`.

Add --mkdir and --rm options

---

README.md

As requested in https://github.com/phonegap/ios-deploy/pull/115

Update README to include --mkdir and --rm

---

ios-deploy.c

Usage:
ios-deploy --uninstall_only --bundle_id my.bundle.id

Adding in standalone uninstall option --uninstall_only

---

LICENSE
errors.h
ios-deploy.c

Fix #157, add text for errors: 0xe8008018, 0xe8008019, 0xe800801c.

Error messages

---

src/ios-deploy.c

Regarding issue #170 -- ran into this myself, put in a new option and set up ios-deploy to skip over devices of type 2 (wifi) for the issue when a device is found on both USB and WIFI.

Added no-wifi option to explicitly skip wifi connectivity.

---

src/ios-deploy/ios-deploy.m

https://twitter.com/panzer/status/712330579291668480
Also fix whitespace

Update for iPhone SE

---

README.md

I have tested the latest version available via npm and it works fine on 10.12.
To reflect this, I have updated the readme.md file.

Updated readme.md showing that it works on 10.12 Sierra.

---

src/scripts/lldb.py

Fixed #301: ios-deploy doesn't handle NSLog

---

src/ios-deploy/device_db.h

We've added some new devices to the device database.

Added new iPad (2017) and iPad Pro 10.5" devices to device DB.

---

README.md

Quick fix from a quick read (should be rebased)

Quick fix for description

---

src/ios-deploy/device_db.h

Added new devices

---

src/ios-deploy/ios-deploy.m

Add JSON output for copying, installing, and launching the debug server.

feat: add JSON output for copy/install/launch

---

LICENSE
README.md

This allows Github to show nice information about the license like https://github.com/orkestra-studios/macula/blob/master/LICENSE
https://help.github.com/en/articles/licensing-a-repository#detecting-a-license has some more info.

Add Full text of GPLv3 license.

---

src/ios-deploy/device_db.h

Add new devices and clean up some repeated defines.

Update Device Definitions

---

src/ios-deploy/ios-deploy.m

This addresses #435
Would like a couple people to look over this. I've run a bunch of tests on my machine... but it's hard to exercise everything this touches.

fixing up static analyzer leak warnings

---

package.json

This was a library with no implementation.

ios-deploy-lib removal

---

src/ios-deploy/ios-deploy.m

50% is reported during transfer and the other 50% during installation phases.

Change progress values during incremental installation to follow the same convention that standard installations follow

---

src/ios-deploy/ios-deploy.m

Forgot to add the long option for -F  before. Sorry

fix: add missing long option for -F/--non-recursively

---

src/ios-deploy/ios-deploy.m

Add --json support for list_bundle_id

---

.gitignore
BUILD.bazel

This allows build rules to add this as their tool dependency.

Support building with Bazel

---

src/ios-deploy/ios-deploy.m

in my opinion these logs are not necessary in non-verbose mode.

Make "Skipping..." log messages verbose only

---

src/ios-deploy/device_db.h

Information from https://www.theiphonewiki.com/wiki/Main_Page

Add iPhone 13 / new iPads / Apple TV 4K 2

---

src/ios-deploy/ios-deploy.m

Start and connect a session prior to downloading device symbols over wifi because fetching the device class (needed to determine the exact dsc_extractor.bundle to use) over wifi requires a session.

Start and connect a session prior to downloading device symbols over wifi
