src/ios-deploy/ios-deploy.m

Added entries for the iPad Air, iPad Air 2, iPad Mini and iPad Mini 3 models.
Also fixed a potential bug where the device detection timeout callback would cause ios-deploy to shut down even if the device had been found.

Add missing iPad Air and iPad Mini models

---

src/ios-deploy/ios-deploy.m

Hello,
We use your work internally in my company, and we needed to deploy automatically on tvOS, so I tweaked the code to allow that. (thanks by the way for continuing ios-deploy :tada: )
Please consider my changes.
Some explaination about the patch : 
- **find_path()** was not working for some paths (I believe it was "iOS DeviceSupport", probably because of the space), so I tweaked it a little bit because my tvOS support path was in this folder.
My fix to this issue has not been to fix **find_path()** per se, but to make it lower level, and escape the paths before calling find_path.
- I added a deviceClassPath variable (2 to be exact, but you can read :+1: ), to adapt with tvOS location, this change is easy to read I believe.
I submit this change from home, so I can't test it with an …

added support for AppleTV OS

---

src/scripts/lldb.py

Fixes #256
In my case the `command = '-X true --'` which makes `args = ['-X true ', '']` and it compleately ignored what we have in `'{args}'`

Fixed a problem with inability to pass arguments through command line parameters

---

src/ios-deploy/ios-deploy.m

The problem looked like a stuck after `(lldb)     autoexit` message in the log.
Before that fix, I had 10-second delay for iPhone 6s and 40 seconds delay (sometimes much longer) for iPad 4. Now the time is comparable to the time of running the game from XCode.
The problem was related to a lack of `target modules search-paths add ...` command which drastically reduces the time of a modules' loading. XCode uses exactly the same lldb command with the same arguments.

Significantly reduced a time of lldb initialization when ios-deploy is used without `--justlaunch` flag

---

ios-deploy.xcodeproj/project.pbxproj
src/ios-deploy/device_db.h
src/ios-deploy/ios-deploy.m

Added additional sdk and arch info to each device entry.
Updated some missing or wrong definitions.
Changed the full name output string format to ~~"device_id a.k.a. 'device_name' (model, sdk, arch)"~~ "device_id (hwmodel, model, sdk, arch) a.k.a. 'device_name'".
It was done to ease some automated testing when working with multiple devices connected to the same Mac (the Apple TV and iOS devices use different SDKs for example). Just thought it might be helpful for others too.

Moved device database to a separate header.

---

src/scripts/lldb.py

- Fixed a problem when the noninteractive mode printed application logs in a wrong order. One line could be inserted into the middle of another one. (The order is very important for us as we parse the logs and retrieve some data automatically)
- Fixed a problem when iosdeploy in noninteractive mode (ran with XCode since version 8.0 only) started to add `(lldb) ` prefixes before it printed a game log. It added this prefixes even in the middle of the line sometimes
- Added handling of additional states

Fixed incorrect logs order in noninteractive mode

---

README.md
src/ios-deploy/ios-deploy.m
src/scripts/lldb.py

Added an option `--detect_deadlocks` which can help to identify an exact state of application's threads in case of a deadlock. It works like this: The user specifies the amount of time ios-deploy runs the app as usual. When the timeout is elapsed ios-deploy starts to print call-stacks of all threads every 5 seconds and the app keeps running. Comparing threads' call-stacks between each other helps to identify the threads which were stuck.

Added an option `--detect_deadlocks`

---

src/ios-deploy/ios-deploy.m

It returns at least internal HardwareModel now.

Fixed: `--detect` didn't return any info for devices missed in the DB

---

src/ios-deploy/ios-deploy.m

Xcode 8.3.3 contains the following directories in
Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport:
10.0			8.1			9.1
10.1			8.2			9.2
10.2			8.3			9.3
10.3.1 (14E8301)	8.4
8.0			9.0
Despite this, this version of Xcode can run code on iOS devices
running iOS 10.3.2 as well.
Therefore try with a pattern of "<version>.*", which for 10.3.2
matches when the last version component has been stripped, into 10.3.
This fixes the latest occurrances of github issue #171.

Look for the developer disk image using more patterns as well

---

src/ios-deploy/ios-deploy.m

It would be useful if a timeout > 0 then when it's reached we kill the running process and return a decent error code.

Return an error code when timeout occurs while running an app.

---

README.md
src/ios-deploy/ios-deploy.m

Comes in hadny when one wishes to attach with an external debugserver client (e.g. a custom lldb or IDA)

add --nolldb (-N): start debugserver without lldb

---

.gitignore
ios-deploy.xcodeproj/project.pbxproj

Linking to private frameworks appears to be disabled on Xcode 9.  As a
workaround, make a temporary local copy before the link step, link
against that, then clean up afterwards.

Add framework copy step before linking

---

src/ios-deploy/ios-deploy.m

I think we don't need to exit the program in 'justlaunch' mode when timeout, because it will kill lldb in case of timeout is small.
Ex: The below code cannot launch the app because it will break after 1s.
```
ios-deploy -t 1 --justlaunch --bundle ./test.app
```

Don't exit program in the justlaunch mode when timeout

---

src/scripts/check_reqs.js

The pre-installation `check_reqs.js` script was checking the Xcode version against a string `'7.0'`. This failed for Xcode 10 and would not let you install ios-deploy.

Fixed Xcode version check for Xcode 10

---

.eslintrc
.eslintrc.yml
package.json
src/scripts/.eslintrc.yml
src/scripts/check_reqs.js

- migrate from jshint to eslint
- JavaScript cleanup to resolve:
- no-trailing-spaces
- no-mixed-spaces-and-tabs
- package.json fixes proposed in #343 are included in this PR as well
Rationale: jshint does not seem to be properly maintained anymore, resulting in some ugly warning messages.
I would be happy to squash some but not all of the commits proposed here.

eslint fixes

---

src/ios-deploy/ios-deploy.m

This code was accidentally removed by a recent merge commit...

Add back to code for --nolldb (-N)

---

src/ios-deploy/ios-deploy.m

the device_id of the new iPhone XS series has changed to a 25 digit hexadecimal string with a '-' character for the 9th character. '-' characters aren't allowed to be file names in python so when the autogenerated python files were imported they would fail with a syntax error due to the new device id being in the name. this sanitized the file names to replace the '-' character with a '_'

sanitize file names that include device_id for iPhone xs series

---

README.md
src/ios-deploy/ios-deploy.m
src/scripts/lldb.py

Sometimes you need to pass environment variables to the remote debugging session just like Xcode. I added the ability to do this.

Add ability to inject arbitrary environment variables

---

src/scripts/check_reqs.js

It would be very odd for anyone to have XCode 6.X or lower at this point. The current check doesn't handle some cases correctly(#378) and adding proper semantic version checking for this seems excessive.

Remove broken XCode version check

---

src/ios-deploy/ios-deploy.m

This seems to have been copied from https://stackoverflow.com/questions/9166291/converting-a-cfstringref-to-char
We can just copy the memory for the c-string from the CFString since we know the UDID doesn't contain any non-ASCII chars.

Remove odd memory copy function

---

src/ios-deploy/ios-deploy.m

#125 
passing --json when running detection will output json dictionaries for each device detected.

Add JSON Output Option

---

src/ios-deploy/MobileDevice.h
src/ios-deploy/ios-deploy.m

This quite a large change, comes dowm to few changes.
- Added `ServiceConnRef` and `AFCConnectionRef` typedefs to better separate when what is used. 
- Fixed some API usege to use functions that work on both WIFI and USB.  This was done in `start_remote_debug_server` and `start_house_arrest_service`. 
- Removed some incorrect `assert` usage, that would break if someone compiled it for release.

Fixup API usage to make ios-deploy work also with wifi connections

---

src/ios-deploy/ios-deploy.m

feat: get battery current capacity

---

src/ios-deploy/ios-deploy.m

Modified lldb command to fix remove_weak_ref issue.

fix: Modified lldb command to fix remove_weak_ref issue

---

src/scripts/lldb.py

If the lldb launch command fails and we are running with --noninteract, the autoexit does not detect that startup has failed and waits until timeout.  
I could repeat the problem while running application that hangs in Framework constructor on the device and in another session trying to launch another ios-deploy session for the same device. 
With this PR, the autoexit will detect that startup failed and return early. I left the logic autoside of run, as it's possbile that someone might want to handle run error in some other way.

Dont hang forever when launching app fails

---

src/ios-deploy/ios-deploy.m

Add codes for errors and send all check_error() errors out as the JSON stream

feat: improve JSON errors

---

src/ios-deploy/ios-deploy.m

The error code being sent for "Device Lock" here was getting sent as -402652958 rather than 3892314338.
Currently  check_error() casts the return to `unsigned int` so also casting the call for image-mounting were correctly sending the expected unsigned value in the JSON; this makes the JSON value for image-mounting issues come through as an unsigned int which can be compared to the hex values that are expected(e.g. 0xe80000e2 = 3892314338, not -402652958 ).

Always send unsigned error codes in JSON

---

src/ios-deploy/ios-deploy.m

LLDB is needed to set args/env, so the args/envs variables are ignored when using nolldb.

Error when passing `args` or `envs` with `nolldb`.

---

README.md

We aren't abandoning the npm package, there are 37 dependent packages on https://www.npmjs.com/package/ios-deploy that we don't want to break!
**BUT**, with the odd issues in #415 it's prudent to not direct people toward node when they are wanting to install ios-deploy for command line use. Directing users to install ios-deploy via brew cuts down the number of steps and seems to be less flaky.

Remove node/npm from README installation steps (in favor of brew)

---

src/scripts/check_reqs.js

This is spurred on by #333 
El Capitan is 4+ years old and this check isn't giving useful information, so just removing the check.
I've never had to use the `--unsafe-perm=true` or any of these other options

Remove El Capitan check

---

src/ios-deploy/MobileDevice.h
src/ios-deploy/ios-deploy.m

This change will leave the standard install as the default option and have no affect on standard installs. Incremental installs needs to be enabled by passing the "--app_deltas" (-A) flag as well as a path to a directory where the mobile device framework will store what it needs to determine what needs has actually changed on a subsequent install.

Add --app_deltas option that can be used to specify a directory to store data to enable incremental installs.

---

src/ios-deploy/ios-deploy.m

Uses the device CPU architecture value to look for `DeviceSupport` path.
When you have two different `DeviceSupport` folders for the same iOS version but different architectures, ios-deploy choses the wrong one for `arm64e` devices. For example, if you have both `'13.3 (17C54)'` and `'13.3 (17C54) arm64e'` in `'Library/Developer/Xcode/iOS DeviceSupport'`, ios-deploy picks `'13.3 (17C54)'`, using the wrong debug symbols when debugging applications on an `arm64e` device.
This change makes ios-deploy also search for the arm64e path when debugging a application on a known `arm64e` device.

Use arch when looking for device support path

---

src/ios-deploy/ios-deploy.m

Print "Disconnected" message when devices disappear.

Print Disconnect message when a device connection is lost

---

src/ios-deploy/ios-deploy.m

Fix the error when try to access some apps' sandbox by using a different command to start house arrest service
By default , when starting house arrest service, it will try to get the full access to the container. But most apps only allow the access to Documents directory.   So `start_house_arrest_service` will fail: 
So I try to start house arrest service by default first. If it fails,  then I will try to start again by VendDocuments. Everything is back to normal.

Fix the error when try to access some apps' sandbox

---

src/ios-deploy/ios-deploy.m

This fixes an analyzer issue introduced in #446 where this options field is actually used

Update AMDeviceCreateHouseArrestService() to have types for options

---

src/ios-deploy/ios-deploy.m

Now `ios-deploy` only support to access app's sandbox.  But actually iOS allows us to browse some other directories on file system,  like `/DCIM` which contains all the photos in camera roll
So I add `-f`(short for `--file_system`) options to work with 5 existing file related options( `download`/`upload`/`mkdir`/`list`/`rm`) .  
When `-f` option is on,  it means the other 5 options is to access the file system, instead of some app's sandbox. 
The code is simple, `-f` decides whether we should start `afc service` or `house arrest service`.  
Usage:
```
ios-deploy -f -l/DCIM
ios-deploy -f -w/DCIM/100APPLE/IMG_001.jpg
ios-deploy -f -R /DCIM/100APPLE/IMG_001.jpg
ios-deploy -f -D/DCIM/test
ios-deploy -f -o/Users/ryan/Downloads/test.png -2/DCIM/test.png
```

Add --file_system/-f option that allows to access the raw file system

---

src/ios-deploy/ios-deploy.m

Now by default, `ios-deploy` will walk the directory recursively .  In our practice , the directory structure may be very complicated and the file operation may cost a lot of time .  
In most cases we  only want to access some specific folder , hope this option may be helpful 
Now list file  option only output the  path of the a file.  
We add `--json` support to get all the meta data of a file , like create time, file size , etc. The meta data will be organized as dictionary .

Add -F/--non-recursively option that controls whether to walk the directory recursively; add --json support for list_file

---

src/ios-deploy/ios-deploy.m

Sometimes, when device is restarted and ios-deploy mounts the new image, user may get "invalid service" error due to race condition while ios is scanning the image. 
While debugging this error, I also received "cannot send message" error in the same place, so I added handling for both errors. 
As the same pattern is repeated a lot of times, added helper function.

handle errors during debugserver startup and add helper function 

---

src/ios-deploy/ios-deploy.m

The error will be handled at the call site in a check_error() call.

Exit early from install/transfer callbacks if the dictionary contains an error. 

---

src/scripts/lldb.py

Python API seems to have removed the lldb.target global variable.  
This works also on Xcode-11.0.

fix lldb script on xcode 12

---

src/ios-deploy/ios-deploy.m

Large apps installed with the incremental flag will timeout in one minute if done when a session is running. Timeouts are common for the initial install of large apps done with the incremental flag.
Remove start/stop/disconnect session calls from calls to AMDeviceSecureInstallApplicationBundle. This version does not seem to need it and it appears this causes errors during long install operations where the session will timeout and reult in kAMDSendMessageError. The standard install method will fail without the start session call.
Information about AMDevice session behavior was gleaned from https://github.com/facebook/idb/blob/8172962dd871805127ad883ce99e75ae0f7bea44/FBDeviceControl/Management/FBAMDevice.h.

Fix Large Incremental Installs

---

src/ios-deploy/MobileDevice.h
src/ios-deploy/ios-deploy.m

Should fix #469 . 
If I did not mess anything up by merging changes this should work on older and newer ios devices.
Added also the version detection for tvOS, but I don't have a device to test this.

fix communication with debuggserver on ios-14

---

src/ios-deploy/ios-deploy.m

If path contains unicode characters, the python script gets some junk.

fix handling of utf8 in output/error paths

---

src/ios-deploy/ios-deploy.m

This is a resubmit of the #338 with a different approach. 
This does not require the custom script to re implement the whole fruitstrap python script, but, if required, override some functionality by specifying own implementation of the function.

feat: add ability to execute custom scripts and commands

---

src/scripts/lldb.py

When lldb session is finished, in some cases the output seems to stay in buffer and never flushed, causing loss of stdout. 
stderr should be unaffected as it should never be buffered.

fix missing output when lldb is buffering output

---

ios-deploy.xcodeproj/project.pbxproj

Seems that noone is using the deadlock timer.

fix script generation to not comment out the first line

---

src/ios-deploy/MobileDevice.h
src/ios-deploy/ios-deploy.m

Should fix #484 . 
Not sure how it worked before 8092250a3c36d34d392497c1824af23d8e24b66f. 
@ryanluoo , can you checks that it fixes issue for you also?

Allocate ref on stack instead of the type itself for AFC service startup

---

README.md

ios-deploy-lib is outdated target as I understand, changed it to ios-deploy

Typo in description

---

src/ios-deploy/ios-deploy.m

I'm using ios-deploy in a scenario where I attach the debugger myself, and having a way to be told the symbol path for that is incredibly useful (and should be no harm, otherwise)

Always emit "Symbol Path: ", even when running `--nolldb`

---

src/ios-deploy/ios-deploy.m

This is really useful when run-in -d indefinitely to keep up with connected devices, as now we can match up the connects top the disconnects keep sync of *how* a device is currently still connected, and when it actually fully disconnected (I.e when you get a matching pair)

Show connection type in "Disconnected" messages

---

src/ios-deploy/ios-deploy.m

This is useful, e.g. for determining if a given device is eligible to run a certain project, depending on Target SDK/Deployment Target.

Show iOS version and build version in "Device found" message

---

src/ios-deploy/MobileDevice.h
src/ios-deploy/device_db.h
src/ios-deploy/ios-deploy.m

This still needs some testing on older macOS/iOS/Xcode versions, but created the PR to get some feedback.  
This PR should allow:
- Detecting watchOS devices connected trough iPhone
- Listing installed bundles
- Uninstalling/Installing on said watchOS device
- Starting debugger and application on said watchOS device
Looks like starting AFC service on watchOS is not possible, so copying files there and back again is also not possible.

Add basic support for watchos

---

src/ios-deploy/ios-deploy.m

This logs the uploaded directories and files in the verbose mode (`-v`)
similar to logging the downloaded directories and files (however that
doesn't require the verbose mode).
Fixes #519.
For example:
```bash
$ ./ios-deploy -v -1 io.realm.Simple --upload=$HOME/Desktop/simple --to=/
[....] Waiting for iOS device to be connected
Handling device type: 1
Already found device? 0
Hardware Model: J72bAP
Device Name: iPadw
Model Name: iPad (2018)
SDK Name: iphoneos
Architecture Name: arm64
Product Version: 14.4.1
Build Version: 18D61
[....] Using X (J72bAP, iPad (2018), iphoneos, arm64, 14.4.1, 18D61) a.k.a. 'iPad'.
/Library/
/Library/Saved Application State/
/Library/Saved Application State/io.realm.Simple.savedState/
/Library/Saved Application …
```

Print uploaded files in verbose mode

---

src/ios-deploy/ios-deploy.m

In some cases, getting path for Symbols or DeveloperDiskImage.dmg took too long (~5-10 seconds) due to inefficient use of find command.
This PR attempts to fix that by limiting find in copy_find_path to specific max depth. The max depth is calculated crudely by simply counting number of forward slashes in the pattern. This brings down the time in my particular case from ~6 seconds to ~0 seconds.

Speed up copy_find_path by specifying maxdepth in find

---

src/ios-deploy/ios-deploy.m

Similar to https://github.com/ios-control/ios-deploy/pull/531, this log not required in normal execution.

Make "Disconnected..." message verbose-only

---

src/ios-deploy/errors.h
src/ios-deploy/ios-deploy.m

That operation always fails with error `0xc` anyway.
To distinguish regular files from FIFO, new `READ_DIR_FIFO` is added to
`read_dir_cb_reason`. The behavior of other operations regarding FIFOs
is left the same by supporting the new reason.
(Another implementation could be not to extend the `read_dir_cb_reason`
and add another flag to `read_dir`'s `callback`, but that would allow
meaningless cases, such as `reason = READ_DIR_AFTER_DIR, is_fifo =
true`.
The ideal implementation would be to extent the `READ_DIR_FILE` enum
case with a flag (i.e., `READ_DIR_FILE(is_fifo = true)`), but that is
not supported in Objective-C.)
The fix is to skip removing FIFOs had a side-effect of failing to remove
a directory where a skipped file is because the directory is not empty.
The change here is to …

Skip removing FIFOs from device

---

src/ios-deploy/ios-deploy.m

xcode-select is able to handle DEVELOPER_DIR pointing to Xcode.app even though
historically it should be pointing to the Contents/Developer sub directory.
This PR restores previous behaviour where setting DEVELOPER_DIR to root xcode folder still works in ios-deploy.
From the `xcode-select` man page:
> Note that for historical reason, the developer directory is considered to be the Developer content directory inside the  Xcode application (for example /Applications/Xcode.app/Contents/Developer). You can set the environment variable to either the actual Developer contents directory, or the Xcode application directory -- the xcode-select provided shims will automatically convert the environment variable into the full Developer content path.

Restore behaviour where DEVELOPER_DIR pointing not Xcode.app still works

---

src/ios-deploy/ios-deploy.m

Update device detection json output to include the interface over which the device was found (e.g. Wifi, USB, etc) and to correctly start a session before fetching device attributes. Previously without a session, devices connected over wifi would return null for some attributes including BuildVersion and DeviceClass.

Update device detection json output to include the interface 

---

src/scripts/lldb.py

Combination of lldb in Xcode-14 and iOS-16 beta currently forwards these events to our handler, which
causes premature exit for the non interact script. Crashes and signals have a reason.

Skipping no reason stops in --non-interact lldb script

---

src/scripts/lldb.py

Add workaround needed for Xcode-13.3+ for --noninteract crashes, where lldb is not able to print backtrace. 
This works both on older lldbs and newer ones, so we don't need some xcode detection.

Add workaround needed for Xcode-13.3+ for --noninteract crashes

---

src/ios-deploy/ios-deploy.m

Add support `--list_processes`, which lists the running processes on the device, along with PIDs.
This PID can be useful to attaching an already running process. Related #525.
The ability to list processes is provided by the `com.apple.instruments.remoteserver` service. This service uses a different communication protocol. The details and the reference implementation is provided by [troybowman/ios_instruments_client](https://github.com/troybowman/ios_instruments_client). I've also referred the implementations at [FBInstrumentsClient.m in facebook/idb](https://github.com/facebook/idb/blob/main/FBDeviceControl/Management/FBInstrumentsClient.m) and [remote_server.py at doronz88/pymobiledevice3](https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/services/remote_server.py). …

Add support for listing running processes

---

src/ios-deploy/ios-deploy.m

Fix #523: Allow server mode for debugserver
With this, when running with `--nolldb`, we create a new debugserver connection every time we accept a connection on the local port and start the proxy loop. This way, multiple connections including simultaneous connections are possible as long as the device is connected.
This still does not behave nicely when device disconnects and reconnects.

Allow multiple connection to debugserver when running with --nolldb

---

src/ios-deploy/ios-deploy.m

Add ability to kill a running process. Adds two options, `--kill` and `--pid`.
`--kill` requires either `--pid` or `--bundle_id` to be specified.

Implement --kill, given pid or bundle id
